# FROM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/python:3.9-slim
FROM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/python:3.11-slim

ADD sources.list /etc/apt/

WORKDIR /app

USER root

RUN echo "deb https://mirrors.huaweicloud.com/debian bullseye main contrib" >>/etc/apt/sources.list
RUN echo "deb https://mirrors.huaweicloud.com/debian-security bullseye-security main contrib" >>/etc/apt/sources.list
RUN echo "deb https://mirrors.huaweicloud.com/debian bullseye-updates main contrib" >>/etc/apt/sources.list
RUN echo "deb https://mirrors.huaweicloud.com/debian/ bookworm main non-free non-free-firmware contrib" >>/etc/apt/sources.list
RUN echo "deb-src https://mirrors.huaweicloud.com/debian/ bookworm main non-free non-free-firmware contrib" >>/etc/apt/sources.list
RUN echo "deb https://mirrors.huaweicloud.com/debian-security/ bookworm-security main" >>/etc/apt/sources.list
RUN echo "deb-src https://mirrors.huaweicloud.com/debian-security/ bookworm-security main" >>/etc/apt/sources.list
RUN echo "deb https://mirrors.huaweicloud.com/debian/ bookworm-updates main non-free non-free-firmware contrib" >>/etc/apt/sources.list
RUN echo "deb-src https://mirrors.huaweicloud.com/debian/ bookworm-updates main non-free non-free-firmware contrib" >>/etc/apt/sources.list
RUN echo "deb https://mirrors.huaweicloud.com/debian/ bookworm-backports main non-free non-free-firmware contrib" >>/etc/apt/sources.list
RUN echo "deb-src https://mirrors.huaweicloud.com/debian/ bookworm-backports main non-free non-free-firmware contrib" >>/etc/apt/sources.list
RUN apt -y update
RUN apt install -y --fix-missing ffmpeg
RUN apt-get update --allow-releaseinfo-change
RUN apt-get install -y ffmpeg
RUN apt-get install -y fonts-arphic-ukai fonts-arphic-uming
RUN apt-get install -y git
RUN apt-get install -y vim

ENV VIRTUAL_ENV=/opt/venv
RUN python -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY requirements.txt .
RUN pip config set global.index-url http://mirrors.aliyun.com/pypi/simple/
RUN pip config set install.trusted-host mirrors.aliyun.com
RUN pip install flask[async]
RUN pip install -r requirements.txt
# RUN pip install bilibili-api-python==16.2.0
RUN pip install git+https://github.com/Nemo2011/bilibili-api.git#main

COPY . /app
RUN python db/init_db.py

EXPOSE 5000
CMD ["python", "src/index.py"]
